// angular-reusable-button/src/app/app.component.ts
import { Component } from '@angular/core';
import { CustomButtonTheme } from './core/enum';

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {

    public CustomButtonTheme = CustomButtonTheme;

    public doSomething($event: MouseEvent): void {
        console.log($event);
    }

}

<app-custom-button
  (buttonClick)="doSomething($event)"
  [theme]="CustomButtonTheme.prime"
  [disabled]="false"
  [label]="'Custom Button'"
></app-custom-button>

<app-custom-button
  (buttonClick)="doSomething($event)"
  [theme]="CustomButtonTheme.secondary"
  [disabled]="false"
  [label]="'Custom Button'"
></app-custom-button>

<app-custom-button
  (buttonClick)="doSomething($event)"
  [theme]="CustomButtonTheme.secondary"
  [disabled]="true"
  [label]="'Custom Button'"
></app-custom-button>

// vue-reusable-button/src/App.vue
<template>
	<CustomButton
		@click="doSomething($event, 'prime')"
		theme="prime"
		label="Custom Button" />
	<CustomButton
		@click="doSomething($event, 'secondary')"
		theme="secondary"
		label="Custom Button" />
	<CustomButton
		@click="doSomething($event, 'disabled')"
		:disabled="true"
		theme="secondary"
		label="Custom Button" />
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import CustomButton from '@/components/CustomButton.vue';

export default defineComponent({
	components: {
		CustomButton,
	},
	methods: {
		doSomething: ($event: MouseEvent, text: string) => {
			console.log(text, $event.target);
		},
	},
});
</script>

<style lang="scss">
body,
html {
	background-color: $second;
	font-size: 10px;
	width: 100%;
	height: 100%;
	margin: 0;
	padding: 0;
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
}

* {
	box-sizing: border-box;
}
</style>
